/*
 * Generated by erpcgen 1.10.0 on Sun May 28 04:53:10 2023.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "remote_control_server.h"
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
#include <new>
#include "erpc_port.h"
#endif
#include "erpc_manually_constructed.hpp"

#if 11000 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

using namespace erpc;
using namespace std;

#if ERPC_NESTED_CALLS_DETECTION
extern bool nestingDetection;
#endif

ERPC_MANUALLY_CONSTRUCTED_STATIC(ControlService_service, s_ControlService_service);



// Call the correct server shim based on method unique ID.
erpc_status_t ControlService_service::handleInvocation(uint32_t methodId, uint32_t sequence, Codec * codec, MessageBufferFactory *messageFactory)
{
    erpc_status_t erpcStatus;
    switch (methodId)
    {
        case kControlService_RemoteControlAction_id:
        {
            erpcStatus = RemoteControlAction_shim(codec, messageFactory, sequence);
            break;
        }

        case kControlService_RemoteTuneSpeed_id:
        {
            erpcStatus = RemoteTuneSpeed_shim(codec, messageFactory, sequence);
            break;
        }

        case kControlService_RemoteShowSpeed_id:
        {
            erpcStatus = RemoteShowSpeed_shim(codec, messageFactory, sequence);
            break;
        }

        case kControlService_RemoteShowPattern_id:
        {
            erpcStatus = RemoteShowPattern_shim(codec, messageFactory, sequence);
            break;
        }

        default:
        {
            erpcStatus = kErpcStatus_InvalidArgument;
            break;
        }
    }

    return erpcStatus;
}

// Server shim for RemoteControlAction of ControlService interface.
erpc_status_t ControlService_service::RemoteControlAction_shim(Codec * codec, MessageBufferFactory *messageFactory, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    uint8_t mode;
    int32_t value;
    double factor;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(&mode);

    codec->read(&value);

    codec->read(&factor);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        RemoteControlAction(mode, value, factor);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBuffer());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset();

        // Build response message.
        codec->startWriteMessage(kReplyMessage, kControlService_service_id, kControlService_RemoteControlAction_id, sequence);

        err = codec->getStatus();
    }

    return err;
}

// Server shim for RemoteTuneSpeed of ControlService interface.
erpc_status_t ControlService_service::RemoteTuneSpeed_shim(Codec * codec, MessageBufferFactory *messageFactory, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    double max;
    double min;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(&max);

    codec->read(&min);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        RemoteTuneSpeed(max, min);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBuffer());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset();

        // Build response message.
        codec->startWriteMessage(kReplyMessage, kControlService_service_id, kControlService_RemoteTuneSpeed_id, sequence);

        err = codec->getStatus();
    }

    return err;
}

// Server shim for RemoteShowSpeed of ControlService interface.
erpc_status_t ControlService_service::RemoteShowSpeed_shim(Codec * codec, MessageBufferFactory *messageFactory, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;


    // startReadMessage() was already called before this shim was invoked.

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        RemoteShowSpeed();
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBuffer());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset();

        // Build response message.
        codec->startWriteMessage(kReplyMessage, kControlService_service_id, kControlService_RemoteShowSpeed_id, sequence);

        err = codec->getStatus();
    }

    return err;
}

// Server shim for RemoteShowPattern of ControlService interface.
erpc_status_t ControlService_service::RemoteShowPattern_shim(Codec * codec, MessageBufferFactory *messageFactory, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;


    // startReadMessage() was already called before this shim was invoked.

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        RemoteShowPattern();
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBuffer());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset();

        // Build response message.
        codec->startWriteMessage(kReplyMessage, kControlService_service_id, kControlService_RemoteShowPattern_id, sequence);

        err = codec->getStatus();
    }

    return err;
}

erpc_service_t create_ControlService_service(void)
{
    erpc_service_t service;

#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    service = new (nothrow) ControlService_service();
#else
    if (s_ControlService_service.isUsed())
    {
        service = NULL;
    }
    else
    {
        s_ControlService_service.construct();
        service = s_ControlService_service.get();
    }
#endif

    return service;
}

void destroy_ControlService_service(erpc_service_t service)
{
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
    erpc_assert(service != NULL);
    delete (ControlService_service *)service;
#else
    (void)service;
    erpc_assert(service == s_ControlService_service.get());
    s_ControlService_service.destroy();
#endif
}

