/*
 * Generated by erpcgen 1.10.0 on Sun May 28 04:53:10 2023.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_remote_control_server_h_)
#define _remote_control_server_h_

#ifdef __cplusplus
#include "erpc_server.hpp"
#include "erpc_codec.hpp"
extern "C"
{
#include "remote_control.h"
#include <stdint.h>
#include <stdbool.h>
}

#if 11000 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


/*!
 * @brief Service subclass for ControlService.
 */
class ControlService_service : public erpc::Service
{
public:
    ControlService_service() : Service(kControlService_service_id) {}

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory);

private:
    /*! @brief Server shim for RemoteControlAction of ControlService interface. */
    erpc_status_t RemoteControlAction_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for RemoteTuneSpeed of ControlService interface. */
    erpc_status_t RemoteTuneSpeed_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for RemoteShowSpeed of ControlService interface. */
    erpc_status_t RemoteShowSpeed_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for RemoteShowPattern of ControlService interface. */
    erpc_status_t RemoteShowPattern_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);
};

extern "C" {
#else
#include "remote_control.h"
#endif // __cplusplus

typedef void * erpc_service_t;

/*! @brief Return ControlService_service service object. */
erpc_service_t create_ControlService_service(void);

/*! @brief Destroy ControlService_service service object. */
void destroy_ControlService_service(erpc_service_t service);

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // _remote_control_server_h_
