/*
 * Generated by erpcgen 1.10.0 on Sun May 28 04:53:10 2023.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_remote_control_h_)
#define _remote_control_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 11000 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief ControlService identifiers */
enum _ControlService_ids
{
    kControlService_service_id = 1,
    kControlService_RemoteControlAction_id = 1,
    kControlService_RemoteTuneSpeed_id = 2,
    kControlService_RemoteShowSpeed_id = 3,
    kControlService_RemoteShowPattern_id = 4,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name ControlService
//@{
void RemoteControlAction(uint8_t mode, int32_t value, double factor);

void RemoteTuneSpeed(double max, double min);

void RemoteShowSpeed(void);

void RemoteShowPattern(void);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _remote_control_h_
