#
# Generated by erpcgen 1.10.0 on Sun May 28 20:10:52 2023.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for BBCarService
class IBBCarService(object):
    SERVICE_ID = 1
    STOP_ID = 1
    GOSTRAIGHT_ID = 2
    TURN_ID = 3
    CTL_MODE_ID = 4
    REMOTECONTROLACTION_ID = 5
    REMOTETUNESPEED_ID = 6
    REMOTESHOWSPEED_ID = 7
    REMOTESHOWPATTERN_ID = 8

    def stop(self, cars):
        raise NotImplementedError()

    def goStraight(self, cars, speed):
        raise NotImplementedError()

    def turn(self, cars, speed, factor):
        raise NotImplementedError()

    def ctl_mode(self):
        raise NotImplementedError()

    def RemoteControlAction(self, mode, value, factor):
        raise NotImplementedError()

    def RemoteTuneSpeed(self, max, min):
        raise NotImplementedError()

    def RemoteShowSpeed(self):
        raise NotImplementedError()

    def RemoteShowPattern(self):
        raise NotImplementedError()


