# You can write copyrights rules here. These rules will be copied into the outputs.

#
# Generated by erpcgen 1.10.0 on Sat Apr 29 20:18:22 2023.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for LCDService
class ILCDService(object):
    SERVICE_ID = 1
    LOC_ID = 1
    CLS_ID = 2
    ROW_ID = 3
    COL_ID = 4
    PUT_ID = 5

    def loc(self, column, row):
        raise NotImplementedError()

    def cls(self):
        raise NotImplementedError()

    def row(self):
        raise NotImplementedError()

    def col(self):
        raise NotImplementedError()

    def put(self, c):
        raise NotImplementedError()


