#
# Generated by erpcgen 1.10.0 on Sun May 28 04:53:38 2023.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for ControlService
class ControlServiceClient(interface.IControlService):
    def __init__(self, manager):
        super(ControlServiceClient, self).__init__()
        self._clientManager = manager

    def RemoteControlAction(self, mode, value, factor):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.REMOTECONTROLACTION_ID,
                sequence=request.sequence))
        if mode is None:
            raise ValueError("mode is None")
        codec.write_uint8(mode)
        if value is None:
            raise ValueError("value is None")
        codec.write_int32(value)
        if factor is None:
            raise ValueError("factor is None")
        codec.write_double(factor)

        # Send request and process reply.
        self._clientManager.perform_request(request)

    def RemoteTuneSpeed(self, max, min):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.REMOTETUNESPEED_ID,
                sequence=request.sequence))
        if max is None:
            raise ValueError("max is None")
        codec.write_double(max)
        if min is None:
            raise ValueError("min is None")
        codec.write_double(min)

        # Send request and process reply.
        self._clientManager.perform_request(request)

    def RemoteShowSpeed(self):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.REMOTESHOWSPEED_ID,
                sequence=request.sequence))

        # Send request and process reply.
        self._clientManager.perform_request(request)

    def RemoteShowPattern(self):
        # Build remote function invocation message.
        request = self._clientManager.create_request()
        codec = request.codec
        codec.start_write_message(erpc.codec.MessageInfo(
                type=erpc.codec.MessageType.kInvocationMessage,
                service=self.SERVICE_ID,
                request=self.REMOTESHOWPATTERN_ID,
                sequence=request.sequence))

        # Send request and process reply.
        self._clientManager.perform_request(request)


