#
# Generated by erpcgen 1.10.0 on Sun May 28 04:53:38 2023.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for ControlService
class IControlService(object):
    SERVICE_ID = 1
    REMOTECONTROLACTION_ID = 1
    REMOTETUNESPEED_ID = 2
    REMOTESHOWSPEED_ID = 3
    REMOTESHOWPATTERN_ID = 4

    def RemoteControlAction(self, mode, value, factor):
        raise NotImplementedError()

    def RemoteTuneSpeed(self, max, min):
        raise NotImplementedError()

    def RemoteShowSpeed(self):
        raise NotImplementedError()

    def RemoteShowPattern(self):
        raise NotImplementedError()


