/*
 * You can write copyrights rules here. These rules will be copied into the outputs.
 */

/*
 * Generated by erpcgen 1.10.0 on Sat Apr 29 20:18:25 2023.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_lcdtext_erpc_server_h_)
#define _lcdtext_erpc_server_h_

#ifdef __cplusplus
#include "erpc_server.hpp"
#include "erpc_codec.hpp"
extern "C"
{
#include "lcdtext_erpc.h"
#include <stdint.h>
#include <stdbool.h>
}

#if 11000 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


/*!
 * @brief Service subclass for LCDService.
 */
class LCDService_service : public erpc::Service
{
public:
    LCDService_service() : Service(kLCDService_service_id) {}

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory);

private:
    /*! @brief Server shim for loc of LCDService interface. */
    erpc_status_t loc_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for cls of LCDService interface. */
    erpc_status_t cls_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for row of LCDService interface. */
    erpc_status_t row_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for col of LCDService interface. */
    erpc_status_t col_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for put of LCDService interface. */
    erpc_status_t put_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);
};

extern "C" {
#else
#include "lcdtext_erpc.h"
#endif // __cplusplus

typedef void * erpc_service_t;

/*! @brief Return LCDService_service service object. */
erpc_service_t create_LCDService_service(void);

/*! @brief Destroy LCDService_service service object. */
void destroy_LCDService_service(erpc_service_t service);

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // _lcdtext_erpc_server_h_
