/*
 * You can write copyrights rules here. These rules will be copied into the outputs.
 */

/*
 * Generated by erpcgen 1.10.0 on Sat Apr 29 20:18:25 2023.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_lcdtext_erpc_h_)
#define _lcdtext_erpc_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 11000 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief LCDService identifiers */
enum _LCDService_ids
{
    kLCDService_service_id = 1,
    kLCDService_loc_id = 1,
    kLCDService_cls_id = 2,
    kLCDService_row_id = 3,
    kLCDService_col_id = 4,
    kLCDService_put_id = 5,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name LCDService
//@{
void loc(int32_t column, int32_t row);

void cls(void);

int32_t row(void);

int32_t col(void);

void put(int32_t c);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _lcdtext_erpc_h_
